[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache"

[[headers]]
  for = "/trails/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

[build.environment]
  NODE_VERSION = "18" 